// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, id int64) error
	GetVideo(ctx context.Context, id int64) (Video, error)
	GetVideoByFilename(ctx context.Context, filename string) (Video, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
