// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CountVideos(ctx context.Context, arg CountVideosParams) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, id int64) error
	GetPeriodStatistics(ctx context.Context, arg GetPeriodStatisticsParams) ([]GetPeriodStatisticsRow, error)
	GetVideo(ctx context.Context, id int64) (Video, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	ListVideosOlderThan(ctx context.Context, startedAt time.Time) ([]Video, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
