// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (filename, title)
VALUES ($1, $2)
RETURNING id, filename, title, status, started_at, finished_at, created_at, updated_at
`

type CreateSessionParams struct {
	Filename string `json:"filename"`
	Title    string `json:"title"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Filename, arg.Title)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentRecordingSession = `-- name: GetCurrentRecordingSession :one
SELECT id, filename, title, status, started_at, finished_at, created_at, updated_at FROM sessions
WHERE status = 'recording'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentRecordingSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getCurrentRecordingSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status = $2,
    finished_at = CASE WHEN $2::VARCHAR = 'completed' OR $2::VARCHAR = 'failed' THEN NOW() ELSE finished_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, filename, title, status, started_at, finished_at, created_at, updated_at
`

type UpdateSessionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
