// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    started_at, finished_at, title, filename
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, started_at, finished_at, title, filename, created_at, updated_at
`

type CreateVideoParams struct {
	StartedAt  time.Time `json:"started_at"`
	FinishedAt time.Time `json:"finished_at"`
	Title      string    `json:"title"`
	Filename   string    `json:"filename"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Title,
		arg.Filename,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVideoFromSession = `-- name: CreateVideoFromSession :one
INSERT INTO videos (filename, title, started_at, finished_at)
SELECT filename, title, started_at, COALESCE(finished_at, NOW())
FROM sessions
WHERE sessions.id = $1
  AND finished_at IS NOT NULL
RETURNING id, started_at, finished_at, title, filename, created_at, updated_at
`

func (q *Queries) CreateVideoFromSession(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideoFromSession, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos
WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, id)
	return err
}

const getVideo = `-- name: GetVideo :one
SELECT id, started_at, finished_at, title, filename, created_at, updated_at FROM videos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, started_at, finished_at, title, filename, created_at, updated_at FROM videos
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListVideosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Title,
			&i.Filename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET
    title = COALESCE($1, title),
    filename = COALESCE($2, filename),
    started_at = COALESCE($3, started_at),
    finished_at = COALESCE($4, finished_at),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, started_at, finished_at, title, filename, created_at, updated_at
`

type UpdateVideoParams struct {
	Title      sql.NullString `json:"title"`
	Filename   sql.NullString `json:"filename"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideo,
		arg.Title,
		arg.Filename,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
