// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_sessions.sql

package sqlc

import (
	"context"
)

const createVideoSession = `-- name: CreateVideoSession :one
INSERT INTO video_sessions (video_id, session_id)
VALUES ($1, $2)
RETURNING id, video_id, session_id, created_at, updated_at
`

type CreateVideoSessionParams struct {
	VideoID   int64 `json:"video_id"`
	SessionID int64 `json:"session_id"`
}

func (q *Queries) CreateVideoSession(ctx context.Context, arg CreateVideoSessionParams) (VideoSession, error) {
	row := q.db.QueryRowContext(ctx, createVideoSession, arg.VideoID, arg.SessionID)
	var i VideoSession
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideoSession = `-- name: DeleteVideoSession :exec
DELETE FROM video_sessions
WHERE id = $1
`

func (q *Queries) DeleteVideoSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVideoSession, id)
	return err
}

const getVideoSessionBySessionID = `-- name: GetVideoSessionBySessionID :one
SELECT id, video_id, session_id, created_at, updated_at FROM video_sessions
WHERE session_id = $1
LIMIT 1
`

func (q *Queries) GetVideoSessionBySessionID(ctx context.Context, sessionID int64) (VideoSession, error) {
	row := q.db.QueryRowContext(ctx, getVideoSessionBySessionID, sessionID)
	var i VideoSession
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoSessionByVideoID = `-- name: GetVideoSessionByVideoID :one
SELECT id, video_id, session_id, created_at, updated_at FROM video_sessions
WHERE video_id = $1
LIMIT 1
`

func (q *Queries) GetVideoSessionByVideoID(ctx context.Context, videoID int64) (VideoSession, error) {
	row := q.db.QueryRowContext(ctx, getVideoSessionByVideoID, videoID)
	var i VideoSession
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
