// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"time"
)

// Error エラーレスポンス
type Error struct {
	Message string `json:"message"`
}

// Pager レスポンスのページネーション情報。
// ページに含まれる対象の数は以下で求められる。
//
// ```
// min(size, totalCount - size * (page - 1))
// ```
type Pager struct {
	// Page ページ番号
	Page int32 `json:"page"`

	// Size 1ページあたりの最大取得件数
	Size int32 `json:"size"`

	// TotalCount ページに含まれているものも含まれていないものも合わせた対象の全数
	TotalCount int32 `json:"totalCount"`
}

// Video 録画ビデオ
type Video struct {
	// AudioActivityRatio 音声アクティビティ率(%)
	AudioActivityRatio float64 `json:"audioActivityRatio"`

	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Filename ファイル名
	Filename string `json:"filename"`

	// FinishedAt 録画終了時刻(UTC)
	FinishedAt time.Time `json:"finishedAt"`

	// Id ビデオID
	Id *int64 `json:"id,omitempty"`

	// StartedAt 録画開始時刻(UTC)
	StartedAt time.Time `json:"startedAt"`

	// Title タイトル
	Title string `json:"title"`

	// UpdatedAt 更新日時
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// VideoCreate ビデオ作成リクエスト
type VideoCreate struct {
	// AudioActivityRatio 音声アクティビティ率(%)
	AudioActivityRatio float64   `json:"audioActivityRatio"`
	Filename           string    `json:"filename"`
	FinishedAt         time.Time `json:"finishedAt"`
	StartedAt          time.Time `json:"startedAt"`
	Title              string    `json:"title"`
}

// VideoPage ビデオページレスポンス
type VideoPage struct {
	Data []Video `json:"data"`

	// Pager レスポンスのページネーション情報。
	// ページに含まれる対象の数は以下で求められる。
	//
	// ```
	// min(size, totalCount - size * (page - 1))
	// ```
	Pager Pager `json:"pager"`
}

// VideoUpdate ビデオ更新リクエスト
type VideoUpdate struct {
	// AudioActivityRatio 音声アクティビティ率(%)
	AudioActivityRatio *float64   `json:"audioActivityRatio,omitempty"`
	Filename           *string    `json:"filename,omitempty"`
	FinishedAt         *time.Time `json:"finishedAt,omitempty"`
	StartedAt          *time.Time `json:"startedAt,omitempty"`
	Title              *string    `json:"title,omitempty"`
}

// VideosListParams defines parameters for VideosList.
type VideosListParams struct {
	// Page ページ番号
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// Size 1ページあたりの最大取得件数
	Size *int32 `form:"size,omitempty" json:"size,omitempty"`
}

// VideosCreateJSONRequestBody defines body for VideosCreate for application/json ContentType.
type VideosCreateJSONRequestBody = VideoCreate

// VideosUpdateJSONRequestBody defines body for VideosUpdate for application/json ContentType.
type VideosUpdateJSONRequestBody = VideoUpdate
