// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/sessions)
	SessionsCreate(c *gin.Context)

	// (PATCH /api/v1/sessions/{id})
	SessionsUpdate(c *gin.Context, id int64)

	// (GET /api/v1/status)
	StatusGet(c *gin.Context)

	// (GET /api/v1/videos)
	VideosList(c *gin.Context, params VideosListParams)

	// (POST /api/v1/videos)
	VideosCreate(c *gin.Context)

	// (DELETE /api/v1/videos/{id})
	VideosDelete(c *gin.Context, id int64)

	// (GET /api/v1/videos/{id})
	VideosGet(c *gin.Context, id int64)

	// (PATCH /api/v1/videos/{id})
	VideosUpdate(c *gin.Context, id int64)

	// (GET /api/v1/videos/{id}/file)
	VideosFile(c *gin.Context, id int64)

	// (GET /api/v1/videos/{id}/thumbnail)
	VideosThumbnail(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SessionsCreate operation middleware
func (siw *ServerInterfaceWrapper) SessionsCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SessionsCreate(c)
}

// SessionsUpdate operation middleware
func (siw *ServerInterfaceWrapper) SessionsUpdate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SessionsUpdate(c, id)
}

// StatusGet operation middleware
func (siw *ServerInterfaceWrapper) StatusGet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StatusGet(c)
}

// VideosList operation middleware
func (siw *ServerInterfaceWrapper) VideosList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params VideosListParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", false, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosList(c, params)
}

// VideosCreate operation middleware
func (siw *ServerInterfaceWrapper) VideosCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosCreate(c)
}

// VideosDelete operation middleware
func (siw *ServerInterfaceWrapper) VideosDelete(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosDelete(c, id)
}

// VideosGet operation middleware
func (siw *ServerInterfaceWrapper) VideosGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosGet(c, id)
}

// VideosUpdate operation middleware
func (siw *ServerInterfaceWrapper) VideosUpdate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosUpdate(c, id)
}

// VideosFile operation middleware
func (siw *ServerInterfaceWrapper) VideosFile(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosFile(c, id)
}

// VideosThumbnail operation middleware
func (siw *ServerInterfaceWrapper) VideosThumbnail(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VideosThumbnail(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/sessions", wrapper.SessionsCreate)
	router.PATCH(options.BaseURL+"/api/v1/sessions/:id", wrapper.SessionsUpdate)
	router.GET(options.BaseURL+"/api/v1/status", wrapper.StatusGet)
	router.GET(options.BaseURL+"/api/v1/videos", wrapper.VideosList)
	router.POST(options.BaseURL+"/api/v1/videos", wrapper.VideosCreate)
	router.DELETE(options.BaseURL+"/api/v1/videos/:id", wrapper.VideosDelete)
	router.GET(options.BaseURL+"/api/v1/videos/:id", wrapper.VideosGet)
	router.PATCH(options.BaseURL+"/api/v1/videos/:id", wrapper.VideosUpdate)
	router.GET(options.BaseURL+"/api/v1/videos/:id/file", wrapper.VideosFile)
	router.GET(options.BaseURL+"/api/v1/videos/:id/thumbnail", wrapper.VideosThumbnail)
}

type SessionsCreateRequestObject struct {
	Body *SessionsCreateJSONRequestBody
}

type SessionsCreateResponseObject interface {
	VisitSessionsCreateResponse(w http.ResponseWriter) error
}

type SessionsCreate200JSONResponse Session

func (response SessionsCreate200JSONResponse) VisitSessionsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SessionsCreatedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SessionsCreatedefaultJSONResponse) VisitSessionsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SessionsUpdateRequestObject struct {
	Id   int64 `json:"id"`
	Body *SessionsUpdateJSONRequestBody
}

type SessionsUpdateResponseObject interface {
	VisitSessionsUpdateResponse(w http.ResponseWriter) error
}

type SessionsUpdate200JSONResponse Session

func (response SessionsUpdate200JSONResponse) VisitSessionsUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SessionsUpdatedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SessionsUpdatedefaultJSONResponse) VisitSessionsUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type StatusGetRequestObject struct {
}

type StatusGetResponseObject interface {
	VisitStatusGetResponse(w http.ResponseWriter) error
}

type StatusGet200JSONResponse RecordingStatus

func (response StatusGet200JSONResponse) VisitStatusGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StatusGetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StatusGetdefaultJSONResponse) VisitStatusGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosListRequestObject struct {
	Params VideosListParams
}

type VideosListResponseObject interface {
	VisitVideosListResponse(w http.ResponseWriter) error
}

type VideosList200JSONResponse VideoList

func (response VideosList200JSONResponse) VisitVideosListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VideosListdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosListdefaultJSONResponse) VisitVideosListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosCreateRequestObject struct {
	Body *VideosCreateJSONRequestBody
}

type VideosCreateResponseObject interface {
	VisitVideosCreateResponse(w http.ResponseWriter) error
}

type VideosCreate200JSONResponse Video

func (response VideosCreate200JSONResponse) VisitVideosCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VideosCreatedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosCreatedefaultJSONResponse) VisitVideosCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosDeleteRequestObject struct {
	Id int64 `json:"id"`
}

type VideosDeleteResponseObject interface {
	VisitVideosDeleteResponse(w http.ResponseWriter) error
}

type VideosDelete204Response struct {
}

func (response VideosDelete204Response) VisitVideosDeleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type VideosDeletedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosDeletedefaultJSONResponse) VisitVideosDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosGetRequestObject struct {
	Id int64 `json:"id"`
}

type VideosGetResponseObject interface {
	VisitVideosGetResponse(w http.ResponseWriter) error
}

type VideosGet200JSONResponse Video

func (response VideosGet200JSONResponse) VisitVideosGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VideosGetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosGetdefaultJSONResponse) VisitVideosGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosUpdateRequestObject struct {
	Id   int64 `json:"id"`
	Body *VideosUpdateJSONRequestBody
}

type VideosUpdateResponseObject interface {
	VisitVideosUpdateResponse(w http.ResponseWriter) error
}

type VideosUpdate200JSONResponse Video

func (response VideosUpdate200JSONResponse) VisitVideosUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VideosUpdatedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosUpdatedefaultJSONResponse) VisitVideosUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosFileRequestObject struct {
	Id int64 `json:"id"`
}

type VideosFileResponseObject interface {
	VisitVideosFileResponse(w http.ResponseWriter) error
}

type VideosFile200VideowebmResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response VideosFile200VideowebmResponse) VisitVideosFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "video/webm")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type VideosFile404JSONResponse Error

func (response VideosFile404JSONResponse) VisitVideosFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VideosFiledefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosFiledefaultJSONResponse) VisitVideosFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VideosThumbnailRequestObject struct {
	Id int64 `json:"id"`
}

type VideosThumbnailResponseObject interface {
	VisitVideosThumbnailResponse(w http.ResponseWriter) error
}

type VideosThumbnail200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response VideosThumbnail200ImagejpegResponse) VisitVideosThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type VideosThumbnail404JSONResponse Error

func (response VideosThumbnail404JSONResponse) VisitVideosThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VideosThumbnaildefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VideosThumbnaildefaultJSONResponse) VisitVideosThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/sessions)
	SessionsCreate(ctx context.Context, request SessionsCreateRequestObject) (SessionsCreateResponseObject, error)

	// (PATCH /api/v1/sessions/{id})
	SessionsUpdate(ctx context.Context, request SessionsUpdateRequestObject) (SessionsUpdateResponseObject, error)

	// (GET /api/v1/status)
	StatusGet(ctx context.Context, request StatusGetRequestObject) (StatusGetResponseObject, error)

	// (GET /api/v1/videos)
	VideosList(ctx context.Context, request VideosListRequestObject) (VideosListResponseObject, error)

	// (POST /api/v1/videos)
	VideosCreate(ctx context.Context, request VideosCreateRequestObject) (VideosCreateResponseObject, error)

	// (DELETE /api/v1/videos/{id})
	VideosDelete(ctx context.Context, request VideosDeleteRequestObject) (VideosDeleteResponseObject, error)

	// (GET /api/v1/videos/{id})
	VideosGet(ctx context.Context, request VideosGetRequestObject) (VideosGetResponseObject, error)

	// (PATCH /api/v1/videos/{id})
	VideosUpdate(ctx context.Context, request VideosUpdateRequestObject) (VideosUpdateResponseObject, error)

	// (GET /api/v1/videos/{id}/file)
	VideosFile(ctx context.Context, request VideosFileRequestObject) (VideosFileResponseObject, error)

	// (GET /api/v1/videos/{id}/thumbnail)
	VideosThumbnail(ctx context.Context, request VideosThumbnailRequestObject) (VideosThumbnailResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// SessionsCreate operation middleware
func (sh *strictHandler) SessionsCreate(ctx *gin.Context) {
	var request SessionsCreateRequestObject

	var body SessionsCreateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionsCreate(ctx, request.(SessionsCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionsCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SessionsCreateResponseObject); ok {
		if err := validResponse.VisitSessionsCreateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SessionsUpdate operation middleware
func (sh *strictHandler) SessionsUpdate(ctx *gin.Context, id int64) {
	var request SessionsUpdateRequestObject

	request.Id = id

	var body SessionsUpdateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionsUpdate(ctx, request.(SessionsUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionsUpdate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SessionsUpdateResponseObject); ok {
		if err := validResponse.VisitSessionsUpdateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StatusGet operation middleware
func (sh *strictHandler) StatusGet(ctx *gin.Context) {
	var request StatusGetRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StatusGet(ctx, request.(StatusGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StatusGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StatusGetResponseObject); ok {
		if err := validResponse.VisitStatusGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosList operation middleware
func (sh *strictHandler) VideosList(ctx *gin.Context, params VideosListParams) {
	var request VideosListRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosList(ctx, request.(VideosListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosListResponseObject); ok {
		if err := validResponse.VisitVideosListResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosCreate operation middleware
func (sh *strictHandler) VideosCreate(ctx *gin.Context) {
	var request VideosCreateRequestObject

	var body VideosCreateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosCreate(ctx, request.(VideosCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosCreateResponseObject); ok {
		if err := validResponse.VisitVideosCreateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosDelete operation middleware
func (sh *strictHandler) VideosDelete(ctx *gin.Context, id int64) {
	var request VideosDeleteRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosDelete(ctx, request.(VideosDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosDelete")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosDeleteResponseObject); ok {
		if err := validResponse.VisitVideosDeleteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosGet operation middleware
func (sh *strictHandler) VideosGet(ctx *gin.Context, id int64) {
	var request VideosGetRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosGet(ctx, request.(VideosGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosGetResponseObject); ok {
		if err := validResponse.VisitVideosGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosUpdate operation middleware
func (sh *strictHandler) VideosUpdate(ctx *gin.Context, id int64) {
	var request VideosUpdateRequestObject

	request.Id = id

	var body VideosUpdateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosUpdate(ctx, request.(VideosUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosUpdate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosUpdateResponseObject); ok {
		if err := validResponse.VisitVideosUpdateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosFile operation middleware
func (sh *strictHandler) VideosFile(ctx *gin.Context, id int64) {
	var request VideosFileRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosFile(ctx, request.(VideosFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosFile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosFileResponseObject); ok {
		if err := validResponse.VisitVideosFileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VideosThumbnail operation middleware
func (sh *strictHandler) VideosThumbnail(ctx *gin.Context, id int64) {
	var request VideosThumbnailRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VideosThumbnail(ctx, request.(VideosThumbnailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VideosThumbnail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VideosThumbnailResponseObject); ok {
		if err := validResponse.VisitVideosThumbnailResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
