// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY/28UxxX/V0bTVrKrxXcGUkX3mwtNZSlSUevkl4DE3O0736Db2c3srBMXncTuBjjH",
	"uFghNnKgAhqIHVyBgdCQmpI/Zrx39k/8C9XMnu/r7tpHTHAUfmLxzcz7vPc+783nzXlcsi3HZsCEiwvn",
	"sVuqgEX05584t7n6MMEtceoIajNcwDJYk+G3Mnwuw3/L4AcZ/lOGT2TwAzaww20HuKCg91vgumQa1KeY",
	"dQAXsCs4ZdO4VjMwh489ysHEhY/aC88Yuwvt4jkoCVwz8CkyDUkgem1L/4EMv1KYgmcyXNAf38twVYZP",
	"GuHF6PYjeSE4zTpL/PVocV36L2RwRQbz0cMX24/uSP9BY2lD+g+3Nu9tPZuX/mrjUSADXwZz8TJ9xml2",
	"9uzZ08yibMSlfwcDCVuQ6gnbYwIdQepP6PdoxCHTgI6g8dFRvX4gNE4rLv1OtfA1l+5HV7/HBi7b3CIC",
	"FzBl4thRbGCLMmp5Fi6Mt2NFmQAVo5qBlfnBY8e7/A6kf0sGnytfb16I7q5GV5ejF9e3Nv/TWNpItEc+",
	"bdnL5/Nd5vNJ5juhyPCtJ/b+N9L/TIU2CFQKg6D/J/++XtD+tS6Dq9K/If1b7aRFF9fSwGeg7aOgTkgr",
	"gD2OJHISOLXNvwkiqCtoyR30tnHz1s7ytebTR9tr9YHkUwFWwp54tQz+JYO7Mrwkw9tbzy5sf7OKjc6O",
	"33Io4wL+Ta5TtLlWxeY6eCYFWDofMXDCOZlt52fQcLRY316rN1aCneVrI83VL0b7YvmH43jP+MUId00k",
	"Ba0P3j7cHwic6XESrz4QFwzsAC8BE4nFGM09jhbrI7/rOcq0vWIVOmcxzyq2uE9FNamkgx+1P3UZrne2",
	"pfTB+Ayj42cPwqSgfkhNsAet7lx53PxyU4bXZHhZBvcHAkk8k9oTJUFnqJj9q7KVcMatJ9HXGzofD1U+",
	"gq/1eeqj+Y/LaXHp7heJBdiJWIkDEWBOJDSLrf/dbNQXG9fvNVaCHjNEwBFBLWWJAzH/wqqzuCC4BwOh",
	"NXCZVoERK7HPLsngjs7LerS4EMN+H9i0qODC0Xfe0cB3/z+eeDSjbiUZexz75tNg67+XGitBVN8c+WDq",
	"xGiaGwNnUzMJcCuTkyeTiJ0Siu6LQRAusvDuLM9Hq/Ovgnd/xB8ywJ5jpnGjceO7xvLGT+JGf+8ysdGu",
	"vTZruoPWk3EjqXy66dwNP7VoT+jlGamOa0CG91X9BWta7dQPZyV3V9pPqqT9Ma6HzEOSdCh4Ke35FSmS",
	"SoVTKWKwRYQuYZutt00iSI++yFIL8c2RIBKcXcGdtTtW5Ukiiqv7SwFJdfcDXRwZDscV/uaY/2vid1+K",
	"1J8oK+tQts7EUx+iiVOT2MAzwN04rvmx/Fhe2bUdYMShuICP6T8p+oiKzk+OODQ3M55ze2TyNIg06ReP",
	"IlgfGuufSRMXunTjxKnJP4PQNjixQAB3ceGjgZx33WTSf9B8+Fl043HjyuXowVcjZW5bo/JCIP1ragLS",
	"a7Y27+2sLEh/Pd4o/etquJhfUgIq+GLnxiWlSv0VGcwrIa4sfOwBn8UGjinRSdd73LZUT9A1st/c1Yxh",
	"HBB2Avxo7kDgT9kHAL5vnkwyWKUWFT2mTCgTryrUVbPHCJo9ANfOqH7kOjZz4x5xNJ9X/5RsJiAeSonj",
	"VGlJsyt3zo1HiQ6QzJbXP/TpYun1fqoCSDVEcAWqEBe5XqkEYII5hvXalpsHhCh+n0mAMcGQx+BTB0oC",
	"TARqGdqNy5jaUDPa5TmjWnJ6aXbkiJ5FU2pU93X3feruWZ2DTxxJFNmdxhMYMuSbyCBDh3gNSSyX+IUg",
	"Adqx/BDvJ/uCmtEJXj6vq2b28vncUO0sdvCwtLOXz+vCTnQho6UN48KrtLTX2UM6cu8X3DwM7Niu2HNy",
	"SWkSrbknFo7gij/a5uzBxrdlodarTtUgWBtI7fjBmh4qrYgwExHE4BMVX9vjJdALigAMtaZJRFxE1M9e",
	"VRz2OyR3npq1mBZVyBT40dznOyt3UwhyMt49cI/oQlfqslPnenDvTXFiuae+YQ7W+vFB2FMV4ICoi5iN",
	"WjFHwkYuMBOVbY5Ehbq7GTZQ0RNIVABVgJjAXWSRWVQE5LlQ9qpj6LCVcvalv/3tk+Z3G5mXfqIi/3ly",
	"lX+DxXv4ejIRpcqeQ3VKElsj+c+Xx9fU+lt+7Kv1v2XPHq08V6bxm0J2j+h+TN+5uLD1450Ukr1Hq3BY",
	"WoV2M/cJFK3e+LbPLlJGtKTsl4dDJvl4fKO83gQrCC7wGeCoRBizBSpTZuprqIUMzLbG+GVwT1Q8q8gI",
	"raYTMHgqw9syXIip1/xyMwqvZl5VU+0zDwkLqUWmIXfOgem3LHzDLKwZOMae9GhxEmagajuWUn7xKmxg",
	"j1dxAVeEcAq5XNUukWrFdkXh3fy7eVw7U/t/AAAA//8hBAJdWCMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
