// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY/28UxxX/V0bTVjLV2nfmSxXdby5uK0tJi1oTCQESc7fvfEN2Zze7swYHneTdLck5",
	"htoKsZETKgMB7EAFJg4NwY75Y8Z7Z//kf6Ga3fV98e6ezwGCo/ITi29m3ue993lvPm+u4JKhmwYDxm1c",
	"uILtUgV0En7+ybIMS36oYJcsanJqMFzAwlsW/rfCXxf+f4T3o/D/LfxV4f2IFWxahgkWpxDu18G2yRjI",
	"Tz5hAi5gm1uUjeFqVcEWfOxQC1RcONtceF7ZXWgUL0KJ46qCT5ExSAPRaVu4j4X/lcTkPRf+9fDjB+Ev",
	"CX+17l8Nbj8Vk9451lriPgpmHwl3Q3jXhDcdPNnYenpHuI/rcyvCfbK5dn/z+bRwl+pPPeG5wpuKloVn",
	"nGMXLlw4x3TK+mz6CSiIG5xoJw2HcdSP5J/Q71GfScYA9aPBI0fC9YnQmHFc9joV42vMPQxmfsAKLhuW",
	"TjguYMr4saNYwTplVHd0XBhsxooyDjJGVQVL88ljB9v89oS7KLzPpa+3JoN7S8HMfLBxc3Ptv/W5lVR7",
	"5HJsL59vs55Ps96KRBfXOkLvPhDuP2VkPU9m0PP2/uQ+DBc0f60Jb0a4Xwt3sZmz4OpyFvYuaPcwMMxH",
	"HL8OR1IpCRY11H9wwqnNaclOelu/tbg9f6Px7OnWci2Re8pBT9kTrRbeXeHdE/6nwr+9+Xxy68ESVlo7",
	"fmtBGRfwb3Ktms3FBZtr4RnhoIf5iIATyyITzfwkDQezta3lWn3B256/0ddY+uLInlj+4TjeN34Rwl0T",
	"aUHbA68H9xOBUx2LRKtfiwsKNsEqAeOptRhMfRfM1vp+13GUajhFDVpnMUcvxtynXEuraO9l6E9N+I9a",
	"2zLaYHSG0vKzA2FaUD+kKhhJq9vXvmt8uSb8G8L/THgPE4EkjkqNoRKn45RP/F3aSjljcTX4ZiXMxxOZ",
	"D++b8Dz50fjXZ1lx2bddtCJWsoBwUIdSmsXmT7fqtdn6zfv1Ba/DDOHQz6kuLVlA1L8xbQIXuOVAIrQK",
	"LlMNGNFT2+yc8O6EeXkUzF6PYL8PbIxXcOHoiRMh8N3/D6YezahdSccexb7xzNt88Wl9wQtqa32nR08e",
	"yXIjcTZV0wDHmRwZTiN2Rija7wVOLN4N7/b8dLA0/XPw9kb8AwbYMdUsbtS//r4+v/JK3Njbu1SsNGuv",
	"yZr2oHVkXEkrn3Y6t8PPLNqT4fIuqY5qQPgPZf15y6HYqR3OSm6vtFeqpN4Y10HmA5L0QPAy2vPPpEgm",
	"FU5laMGYCG26trvcVgknHfqim1qIbo4UkWDu6u1uuyNRniaiLHl/SSCZ7p4Oi6OLw1GFvz3m/z/xe0+K",
	"5J8oK4ehjM/Eox+ioVMjWMHjYNlRXPMD+YG8tGuYwIhJcQEfC/8k6cMrYX5yxKS58cGc3SGTx4BnSb9o",
	"EsHhoZH+GVFxoU03Dp0a+Qvw0IZFdOBg2bhwNl16YwXDZVMzVMCFMtFskH7hAv7YAWsCKzhKp5RX1FBx",
	"O42jGyMiuoQKTLa9s1glct8lgI9kczQYr7RRvBXRhIzsnK96AaVRnUo3WxhUKBNH47hwovcJbTBNsyfQ",
	"Lb6ov5iv37y/s147c+bMmf4PPugfHg5+uhusz+ysT/UIuEhsGJY13Y5538jsKoTbwtsIHxNWd9ZrI0N/",
	"HUKS5Z8YDJBsJPLwCJCYdDc3pnfWvxqyKcmNGh9NGDvrU2LSi1IuR8G7fmPumvC+2FquNR7fFO6CnC3d",
	"x8JdCl5e3Xrg9ujQLoD0JODToydTtPx5ySLbNJgdNaij+bz8p2QwDtFETExTo6WQ2rmLdjTHtM7v2m/3",
	"TpxhpXbGc7QCSNIYbI4qxEa2UyoBqKAO4HBtjP41IYrehlJgDDHkMLhsQomDikAuQ7txGZAbqkqzN4zL",
	"+yC7L7S0UDgIZzSI8FKx36f2vq0h+bzSU4+InwaSRBg84PtMsgYO8DLTC9T4+SIF6rH8q3WON0nulgj6",
	"FbNawaZh8331fAZ742kguofA5n801InXG9/YQrVTs8nLrppI7eDrNX2gtCLCVEQQg0syvoZjlSBcUARg",
	"KJ6xELERkT87Gj/szS13harViBYadJW9wdTn2wv3MggyHO1ONLiwC0jN1WoCtLue2f9lL1nrx5OwRytg",
	"AaI2YgaKY464gWxgKiobFuIVau9mWEFFhyNeAVQBooJlI51MoCIgx4ayow2gw1bK3W+jrW9XG9+vdL2N",
	"UnXqL5Or/Fss3sPXkwkvVfYdNTOSGA+qv1we31Drj/3oqfW/Y88+rTxXptGk3b1HtD8xb1+9vvnyTgbJ",
	"/kw1OCytInQzdwmKemd8m2cXKSOh3tw7+xwwycejG+XNJlhCsMEaBwuVCGMGR2XK1PAaipGB2tQYvw7u",
	"8YqjFxmhWjYBvWdyovavR9RrfLkW+DNdr6rR5pmHhIVUJ2OQu2jC2DsWvmUWVhUcYU+bpodhHDTD1KXy",
	"i1ZhBTuWhgu4wrlZyOU0o0S0imHzwnv59/K4er76vwAAAP//9crYJW0iAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
