// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYbW/cxhH+K4ttC8gFrTv5pQj4TbXbQkCAGq2SL7YB75FzunXJJbO7lK0aB/jIOjnH",
	"cS3UsQI3Lmw3TqTYRSzHceNUrfNjVryT/kWxJHVvJO9OiRMrSD6JOu7uPPPMM7MzvIQtz/U9BkwKbF7C",
	"wmqAS5LH33Ducf1gg7A49SX1GDaxCjdU9KmK/quif6nwKxX9Q0VPVfgVNrDPPR+4pJDsd0EIsgT6Ua74",
	"gE0sJKdsCTebBubwVkA52Ng83Vt41thb6NXOgyVx08CnyBIUgRi2rVqfqejvGlP4XEXXk4cvVbSuoqed",
	"6Ep874m6HJ5h/SWtR/HqI9V6ocL3VHgtfvxi58l91fqsc2tTtR5vb328/fyaaq13noQqbKnwarosOeMM",
	"O3fu3BnmUjYj6J/BQNKTxDnhBUyiw0j/hH6JZnyyBOgwmjt0KFmfo8bPeBl1KsPXvfUwvvElNnDd4y6R",
	"2MSUyaNHsIFdyqgbuNic63FFmQTNUdPA2nz+2LkBv0PVuqvCd7Wvdy7HD9bjG2vxiw+2t/7dubVZaI9c",
	"zOxVqwPWq0XW+0yMcW2I+tYnqvUXzWwY6giG4eir1sNkQe9tW4U3VOtD1brbi1l8ZaMM+xi0IwpM4pHx",
	"N+RIoSSBU8/+oySSCkktkfe2c+fu7trN7rMnOxvtXOypBLdgT7pahf9U4QMVva2ie9vPL+98so6N/o6f",
	"c6hjE/+s0s/ZSpawlT6eBQluEo8UOOGcrPTikzccr7Z3Ntqd2+Hu2s2Z7vrfDo1w+atjeCJ/KcI9E0Wk",
	"jcCbwv0ccXbASbr6pbhgYB+4BUwW5mJ89fN4tT3zi6GjbC+oOdA/iwVuLdM+lU5RRodfJ/60VfSov62k",
	"DKZnGH0/hxAWkfomtcHLW9197/Pu+1squqmid1T4MEckCWzqzVuSLlO58gdtq+CMu0/jjzaTeDzW8Qg/",
	"Ss7TD92/vlPGy8Ry0WfM4kAk2PMFxWL7f3c67dXOBx93bodDZoiEw5K62hIHYv+eOSvYlDyAHLUGrlMH",
	"GHELy+wtFd5P4vIoXr2ewn4d2JJsYPPI8eMJ8L3/5wqPZlQ0irGn3Hefhdv/ebtzO4zbWzNvLJ44VOZG",
	"7mxqFwHOIrlwskjYJVQM3guScDkO7+7atXj92jfBO53w90lw4Ntl2uh8+EVnbfNbaWO0dtnY6OVeTzWD",
	"pA1F3ChKn0E5D8IvTdoTyfIxoU5zQEUPdf6FG0mz0z6YmTyYad8qk6ZT3JCY9ynSfcErKc/fUCKlUjhV",
	"0gtmQhjoa8e32zaRZKi/GNctpDdHQZPg7/Xb43anTXlRE8X1/aWBlLr7RpIcYxxOM/zVKf/HpO+REOmf",
	"KKsnVGZn4sU30fypBWzgZeAi5bU6W52tarueD4z4FJv4aPKTlo9sJPGpEJ9WlucqYqhNXgJZ1vqlkwhO",
	"Dk37nwUbmwN94/yphd+BTGxw4oIELrB5urj1xgaGi77j2YDNOnEEaL+wid8KgK9gA6fh1O0V9Ww8KOP0",
	"xkiFrqEC02XvNLaJ3ncB4E+6OHpMNgYk3mc010YOz1fTgHKoS7WbfQw21EngSGwen35CK5gPm2e1o8L3",
	"mEhz6Ei1qv9YHpOQDm3E9x1qJexXzou01e7jGFsSRoeiREzDZCw2AGmmQUjUIAKJwLIAbLBncbI28/Il",
	"IUo/XxTAmGcoYHDRB0uCjUAvQ3u8zOoNTaMn32Vdssql27+uk1mtRMNJ3ROvUzFRvfkvAFPJOJte84KZ",
	"2+cnhLyA9/HxYBqo2YRdAPVo9eCKu39P/4BVbWDfE3Jiy1mi3qxhTUslCPlrz155ufxmFprDbYWux81c",
	"aOderul9hRURZiOCGFzQ/HoBtyBZUANgKBsDEBGI6NeBIw96catconYzlYUDYzuz+Oq7u7cflAjkZLo7",
	"V+CSKqDbgn4RoOOv3Mkfn/K5fiwPe7EBHBAViHko4xxJDwlgNqp7HMkGFXsRNlAtkEg2ADWA2MAFcskK",
	"qgEKBNQDZxYdtFQefxvtfPq0+8Xm2NuosJX6fmJVfYXJe/BqMpFWY+I0VBLEbJb6/uL4HZX+zI+pSv9P",
	"6plQyit6Xp3csQ5+Bd29cn376/slIvstdeCglIrEzcoFqLnD/PbOrlFGkn5zdDLbZ5CPpTfKdxtgDUEA",
	"XwaOLMKYJ1GdMju5hjJkYPd6jB+G9mQjcGuMUKdcgOEzFd1T0fVUet33t+LoxtirarF35gFRIXXJElTO",
	"+7D0kwpfsQqbBk6xF03TJ2EZHM93deeXrsIGDriDTdyQ0jcrFceziNPwhDRfq75Wxc2zzf8HAAD//wCh",
	"WHAQIQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
