/* tslint:disable */
/* eslint-disable */
/**
 * TV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * エラーレスポンス
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 録画ビデオ
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * ビデオID
     * @type {number}
     * @memberof Video
     */
    'id': number;
    /**
     * 録画開始時刻
     * @type {string}
     * @memberof Video
     */
    'startedAt': string;
    /**
     * 録画終了時刻
     * @type {string}
     * @memberof Video
     */
    'finishedAt': string;
    /**
     * タイトル
     * @type {string}
     * @memberof Video
     */
    'title': string;
    /**
     * ファイル名
     * @type {string}
     * @memberof Video
     */
    'filename': string;
    /**
     * 作成日時
     * @type {string}
     * @memberof Video
     */
    'createdAt': string;
    /**
     * 更新日時
     * @type {string}
     * @memberof Video
     */
    'updatedAt': string;
}
/**
 * ビデオ作成リクエスト
 * @export
 * @interface VideoCreate
 */
export interface VideoCreate {
    /**
     * 
     * @type {string}
     * @memberof VideoCreate
     */
    'startedAt': string;
    /**
     * 
     * @type {string}
     * @memberof VideoCreate
     */
    'finishedAt': string;
    /**
     * 
     * @type {string}
     * @memberof VideoCreate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof VideoCreate
     */
    'filename': string;
}
/**
 * ビデオ一覧レスポンス
 * @export
 * @interface VideoList
 */
export interface VideoList {
    /**
     * 
     * @type {Array<Video>}
     * @memberof VideoList
     */
    'videos': Array<Video>;
    /**
     * 
     * @type {number}
     * @memberof VideoList
     */
    'total': number;
}
/**
 * ビデオ更新リクエスト
 * @export
 * @interface VideoUpdate
 */
export interface VideoUpdate {
    /**
     * 
     * @type {string}
     * @memberof VideoUpdate
     */
    'startedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoUpdate
     */
    'finishedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoUpdate
     */
    'filename'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ビデオ作成
         * @param {VideoCreate} videoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosCreate: async (videoCreate: VideoCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoCreate' is not null or undefined
            assertParamExists('videosCreate', 'videoCreate', videoCreate)
            const localVarPath = `/api/v1/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(videoCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ビデオ削除
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('videosDelete', 'id', id)
            const localVarPath = `/api/v1/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ビデオ詳細取得
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('videosGet', 'id', id)
            const localVarPath = `/api/v1/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ビデオ一覧取得
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosList: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ビデオ更新
         * @param {number} id 
         * @param {VideoUpdate} videoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosUpdate: async (id: number, videoUpdate: VideoUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('videosUpdate', 'id', id)
            // verify required parameter 'videoUpdate' is not null or undefined
            assertParamExists('videosUpdate', 'videoUpdate', videoUpdate)
            const localVarPath = `/api/v1/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(videoUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * ビデオ作成
         * @param {VideoCreate} videoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async videosCreate(videoCreate: VideoCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Video>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.videosCreate(videoCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.videosCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ビデオ削除
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async videosDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.videosDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.videosDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ビデオ詳細取得
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async videosGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Video>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.videosGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.videosGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ビデオ一覧取得
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async videosList(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VideoList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.videosList(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.videosList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ビデオ更新
         * @param {number} id 
         * @param {VideoUpdate} videoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async videosUpdate(id: number, videoUpdate: VideoUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Video>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.videosUpdate(id, videoUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.videosUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * ビデオ作成
         * @param {VideoCreate} videoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosCreate(videoCreate: VideoCreate, options?: RawAxiosRequestConfig): AxiosPromise<Video> {
            return localVarFp.videosCreate(videoCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * ビデオ削除
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.videosDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * ビデオ詳細取得
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Video> {
            return localVarFp.videosGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * ビデオ一覧取得
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosList(limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<VideoList> {
            return localVarFp.videosList(limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * ビデオ更新
         * @param {number} id 
         * @param {VideoUpdate} videoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        videosUpdate(id: number, videoUpdate: VideoUpdate, options?: RawAxiosRequestConfig): AxiosPromise<Video> {
            return localVarFp.videosUpdate(id, videoUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * ビデオ作成
     * @param {VideoCreate} videoCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public videosCreate(videoCreate: VideoCreate, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).videosCreate(videoCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ビデオ削除
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public videosDelete(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).videosDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ビデオ詳細取得
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public videosGet(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).videosGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ビデオ一覧取得
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public videosList(limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).videosList(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ビデオ更新
     * @param {number} id 
     * @param {VideoUpdate} videoUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public videosUpdate(id: number, videoUpdate: VideoUpdate, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).videosUpdate(id, videoUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}



